# -*- coding: utf-8 -*-
"""tour_app_model_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mq3FzAC2f_sqkX9qCN2WT0LP8vO7wT4d
"""

#libraries
!pip install fuzzywuzzy
!pip install python-Levenshtein


import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics.pairwise import cosine_similarity

# Load dataset from CSV file
csv_file_path = '/content/dataset_csv_file.csv'  # Replace with your CSV file path
data = pd.read_csv(csv_file_path)

# Convert numerical columns to proper data types
data['Popularity/Ratings'] = pd.to_numeric(data['Popularity/Ratings'], errors='coerce')
data['Attraction Location (Latitude)'] = pd.to_numeric(data['Attraction Location (Latitude)'], errors='coerce')
data['Attraction Location (Longitude)'] = pd.to_numeric(data['Attraction Location (Longitude)'], errors='coerce')
data['Restaurant Location (Latitude)'] = pd.to_numeric(data['Restaurant Location (Latitude)'], errors='coerce')
data['Restaurant Location (Longitude)'] = pd.to_numeric(data['Restaurant Location (Longitude)'], errors='coerce')

# Handle missing values
data.fillna(-1, inplace=True)

# Label Encoding for categorical features
label_encoder = LabelEncoder()
data['Continent_encoded'] = label_encoder.fit_transform(data['Continent'])
data['Type of Attraction'] = data['Type of Attraction'].astype(str)
data['Type of Attraction_encoded'] = label_encoder.fit_transform(data['Type of Attraction'])
data['Best Time to Visit'] = data['Best Time to Visit'].astype(str)
data['Best Time to Visit_encoded'] = label_encoder.fit_transform(data['Best Time to Visit'])
data['Preferred Cuisines'] = data['Preferred Cuisines'].astype(str)
data['Preferred Cuisines_encoded'] = label_encoder.fit_transform(data['Preferred Cuisines'])

# Select features for recommendation
features = ['Continent_encoded', 'Type of Attraction_encoded', 'Popularity/Ratings', 'Best Time to Visit_encoded', 'Preferred Cuisines_encoded']

# Final feature matrix
X = data[features]

# Calculate cosine similarity between attractions
similarity_matrix = cosine_similarity(X)

# Function to get recommendations based on a given attraction
def get_recommendations(attraction_name, similarity_matrix, data, top_n=3):
    idx = data[data['Attraction Name'] == attraction_name].index[0]
    sim_scores = list(enumerate(similarity_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n + 1]
    attraction_indices = [i[0] for i in sim_scores]
    return data['Attraction Name'].iloc[attraction_indices]

# --- Updated function for user preferences ---
def recommend_based_on_user_preferences_with_presentation(user_continent, user_attraction_type, user_cuisine, data, similarity_matrix, top_n=3):
    # Filter data based on user's preferences
    user_filtered_data = data[
        (data['Continent_encoded'] == user_continent) &
        (data['Type of Attraction_encoded'] == user_attraction_type) &
        (data['Preferred Cuisines_encoded'] == user_cuisine)
    ]

    # If no results found, try broader matching
    if user_filtered_data.empty:
        broad_filtered_data = data[
            (data['Continent_encoded'] == user_continent) |
            (data['Type of Attraction_encoded'] == user_attraction_type) |
            (data['Preferred Cuisines_encoded'] == user_cuisine)
        ]

        if broad_filtered_data.empty:
            return "No attractions match your preferences. Try adjusting your filters."

        random_idx = broad_filtered_data.sample(1).index[0]
    else:
        random_idx = user_filtered_data.sample(1).index[0]

    sim_scores = list(enumerate(similarity_matrix[random_idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n + 1]
    attraction_indices = [i[0] for i in sim_scores]

    presentation = f"\n### 🌍 Attraction Based on Your Preferences ###\n"
    random_attraction = data.iloc[random_idx]

    presentation += f"\n**✨ {random_attraction['Attraction Name']} ({random_attraction['City Name']}, {random_attraction['Country Name']})**\n"
    presentation += f"![Image]({random_attraction['Image_Link']})\n"  # Add the image link here
    presentation += f"A beautiful {random_attraction['Type of Attraction']} located in {random_attraction['City Name']} with a rating of {random_attraction['Popularity/Ratings']}."
    presentation += f"\n\n**Best Time to Visit**: {random_attraction['Best Time to Visit']}"
    presentation += f"\n\nNearby Restaurant: {random_attraction['Restaurant Name']} serving {random_attraction['Preferred Cuisines']} cuisine."
    presentation += f"\nAmenities: {random_attraction['Amenities']}"

    presentation += f"\n\n### 💡 Top Recommendations Similar to {random_attraction['Attraction Name']} ###\n"

    for i, rec_idx in enumerate(attraction_indices):
        recommended = data.iloc[rec_idx]
        presentation += f"\n{i+1}. **🚠 {recommended['Attraction Name']} ({recommended['City Name']}, {recommended['Country Name']})**\n"
        presentation += f"![Image]({recommended['Image_Link']})\n"  # Add the image link for recommendations
        presentation += f"- **Why Visit?**: A {recommended['Type of Attraction']} rated {recommended['Popularity/Ratings']} located in {recommended['City Name']}. "
        presentation += f"Perfect to visit during {recommended['Best Time to Visit']}."
        presentation += f"\n- **Cuisine Nearby**: {recommended['Restaurant Name']} ({recommended['Preferred Cuisines']} cuisine)"
        presentation += f"\n- Amenities: {recommended['Amenities']}\n"

    return presentation

# Get unique categories for continent, attraction type, and cuisine from the dataset
unique_continents = data['Continent'].unique().tolist()
unique_attraction_types = data['Type of Attraction'].unique().tolist()
unique_cuisines = data['Preferred Cuisines'].unique().tolist()

label_encoder_continent = LabelEncoder()
label_encoder_attraction_type = LabelEncoder()
label_encoder_cuisine = LabelEncoder()

label_encoder_continent.fit(unique_continents)
label_encoder_attraction_type.fit(unique_attraction_types)
label_encoder_cuisine.fit(unique_cuisines)

from fuzzywuzzy import process

# Function to get user preferences with fuzzy matching
def get_user_preferences():
    while True:
        user_input = input(f"Enter your preferred continent, attraction type, and cuisine (comma-separated):\nContinent: {unique_continents} \nType of Attraction: {unique_attraction_types}\nCuisine: {unique_cuisines} \n")
        user_preferences = [pref.strip() for pref in user_input.split(',')]

        # Check if user provided exactly three preferences
        if len(user_preferences) != 3:
            print("Please provide exactly three values: continent, attraction type, and cuisine.")
            continue

        user_continent_input, user_attraction_type_input, user_cuisine_input = user_preferences

        # Fuzzy match continent
        user_continent = process.extractOne(user_continent_input, unique_continents)
        user_attraction_type = process.extractOne(user_attraction_type_input, unique_attraction_types)
        user_cuisine = process.extractOne(user_cuisine_input, unique_cuisines)

        # Check if we found close matches
        if user_continent[1] < 70 or user_attraction_type[1] < 70 or user_cuisine[1] < 70:
            print("One or more inputs are unclear. Please try again with clearer options.")
            continue

        # Get the best matches
        user_continent_index = unique_continents.index(user_continent[0])
        user_attraction_type_index = unique_attraction_types.index(user_attraction_type[0])
        user_cuisine_index = unique_cuisines.index(user_cuisine[0])

        return user_continent_index, user_attraction_type_index, user_cuisine_index

# Get user preferences
user_continent, user_attraction_type, user_cuisine = get_user_preferences()

# Get recommendations based on user preferences
user_recommendations_presentation = recommend_based_on_user_preferences_with_presentation(
    user_continent, user_attraction_type, user_cuisine, data, similarity_matrix
)

# Display the recommendations
print(user_recommendations_presentation)